version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: case-study
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"

volumes:
  db_data:
